name: test

on:
  push:
    paths-ignore:
      - "**/README.md"
  pull_request: {}

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: go test -v -race -coverprofile=coverage.txt ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: unit

  integration-enterprise:
    strategy:
      matrix:
        kong_version:
          [
            "3.0",
            "3.1",
            "3.2",
            "3.3",
            "3.4",
            "3.5",
            "3.6",
            "3.7",
            "3.8",
            "3.9",
            "3.10",
            "3.11",
            "3.12",
          ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          cwd: ${{ github.workspace }}/docker-compose
        env:
          KONG_DOCKER_TAG: kong/kong-gateway:${{ matrix.kong_version }}
          KONG_DATABASE: postgres

      - name: Run tests
        run: go test -v -race -run TestIntegration -tags integration,enterprise -coverprofile=coverage.txt ./...
        env:
          TEST_KONG_VERSION: ${{ matrix.kong_version }}
          GOTOOLCHAIN: go1.25.1+auto

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: integration

  integration-oss:
    strategy:
      matrix:
        kong_version: ["3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2
        with:
          cwd: ${{ github.workspace }}/docker-compose
        env:
          KONG_DOCKER_TAG: kong/kong:${{ matrix.kong_version }}
          KONG_DATABASE: postgres

      - name: Run tests
        run: go test -v -race -run TestIntegration -tags integration -coverprofile=coverage.txt ./...
        env:
          TEST_KONG_VERSION: ${{ matrix.kong_version }}
          GOTOOLCHAIN: go1.25.1+auto

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          flags: integration
